osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients: "-fodeguipro@gmail.com -henri.m.gil@gmail.com -ismadia09@gmail.com"
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: GurpyBJVZzXNqYX6lhz383uYgZ2HR2PaTjql6GPvtv54behf4mpffhQs3NHF5f8hpqmL+lYCQ6YddixCXN/nr9ZxuA1XA69SyaycUcU93qxP9MEF50BNzqxzNpBgJYcppJlM2eU1S2aeTtGYn+9sK0xPFN9pDtKyhMF1q77d8glkhlf63WJK1fq9RRc5VkrG4Urui89Yst+GB3Q2rXNvVtieZupeulgTfQeTygyVrPQyAEbDg/+Hx1rFavN0jCZ0vpkYARRDJ+jWqrSXaZ6v8ZSeKSUO9l5/ruTOKxtjCOxtS68Xy9h7TnT/8i/GI6JjsDDTz7311qfYQtz0crdnyWp5kBKs4sa9oYiWXYDaQlajx9uTEIN2thtdJ8g7b2zxhiDY3cwW/qviOh00DRw5GY2fjtCW384IcIZjvhctGfBxyLHBv7IFn3o5KmdR9+yqCqVof0+3Hxfna6u+szPP+cCpGNbK7yOgAIOk11sRK1HmGEssURY2Jg1TvM5yqBDczF040J3S3yUtwcQFN99tTgRmcTjFYzh04sHwOawECn6xn5uiTDSR3qlIK/tNV/Ad+nwb2dm5S3z/0pcc2A+krDZWjts4n+4MZPbYR9a/K0JuQjQTsGslAozdhXzcVfHfuAfJCl6xFLEAgvbn2sytjB3YF5ChjRFWjZkWInBmoYY=
before_install:
  - gem install bundler
  - bundle install

deploy:
  provider: releases
  apikey:
    secure: tSEA7qRcCYgUK+bDr8fbGnxTjOpVhK1Ju98JdRQiGwPBVFQ7+n68Xg03GAwG70x0QQzBfes4yOpXrg5DJ/V+2JFpZqeY0n+dyo2eKzMIjSZ2pvtfoO0HlumQ7mmTwj8QAKwJGcloZEG6zXx0CzVWun8C4DW7rTzgeHEAdCOuWxpKX40S7cgBOa1+t2MnX0/iEdrJhsV6eJc2aRmhKiL3darSDchQWE+wzwbf6WHMM54etLFeKvm+EJRZ3QnKD+mT529aucHT2h5YZhqjJAwp1Rmhi9ut7CPvySq0VjKwzgLQMt2SBXcTp7HlBVaAnnX9ZOpBeHA5IuZTqbQ34KdDBLXY7XmcVyD75tKJym5lzvtWMvSARtzzmYbf8sW9+BJAnDmxXWZ25nGRi4NmbUPtg7//HNgCAuAQWheWJr4fPVBZARIsbCYUiWxEf62sMa7OstUdY2BOjcOnsAkwKsjqlvJ3SjzniUwC9SSBRoWFfPs5X/AqkGeXCE1MY/nbIIMVpCmth8SbshVBEBw49Q3OKWmKGExYpVQzESjk5FOG68wdH96jnyLH3i4VIkBqBkOClUAOvzSzii0hiEc77kZqzb2KKJAjka+ISBn47GLejk3vts4p9WL/5wU1eluSQoISxOmj9JjoWcZ5o96DUrghP3+ILARdZrPxrW5HO9/bR6o=
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: YkN5KqqIKOyRMm/QfZtQz7AXvt+UcN+wzHxyKh9saNgYH/20NdV7UyRIZ3WEovZn/BXsaLRk0K6vOE+V5ZAjXu6pMd7qtpYsTqdolR+kdjGB8qu+Gj9RpNyvJWV9Gb6dEkf+pYC1dYGNmDQRMeSQG+E9ZE99kjooWT03eoCx5xaRVNqFXFvT0hGUOrZL3BTnamKFqR/N258/pl8kTubiQ/Xq2kbDU4Ed8E6gKAByF9fzTCyViBTnLYAi/C3uEbn7Fa1xmBDwGLuwfpFfii9m3gCzRJ5qUJa1Rrk8gGJ/dWmHoQNxFBG3kSqJ3GphgOvxW9vwE8Ta4zNu0mfSRfUEgzC8V0BiKUkNWGolowxvsRIfM1MgqU7SC/le4SXxopH+9m4j2Ec84pWVB6d5dNfFDXkcSIX7HviitCQCk3R6uVyBHxCFQ9zA8JK8zJM7Nh0UneP7D6w4GEdxqtETt5TVjjUlBhw8XEPzM2/75TWdh1u//HDKoz1XJfmvx5KcJGwPOu5sOtuuYlpyO5489emYE0YK9sOkyHDOjqs2P7C1yiHsvjEbPjYb/BW41hj/TaqfX0/jgJyo2vGvuHHibQSC6jfOT5qM/tJePhmqzFmS+he57FZyAi1wlPH3ZEdjpWo+edFy4iKui3R7TqFGC35UJILUgrF1yD7adkqQqPypD6w=

script: bundle exec fastlane beta
