osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients: "-fodeguipro@gmail.com -henri.m.gil@gmail.com -ismadia09@gmail.com"
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: GurpyBJVZzXNqYX6lhz383uYgZ2HR2PaTjql6GPvtv54behf4mpffhQs3NHF5f8hpqmL+lYCQ6YddixCXN/nr9ZxuA1XA69SyaycUcU93qxP9MEF50BNzqxzNpBgJYcppJlM2eU1S2aeTtGYn+9sK0xPFN9pDtKyhMF1q77d8glkhlf63WJK1fq9RRc5VkrG4Urui89Yst+GB3Q2rXNvVtieZupeulgTfQeTygyVrPQyAEbDg/+Hx1rFavN0jCZ0vpkYARRDJ+jWqrSXaZ6v8ZSeKSUO9l5/ruTOKxtjCOxtS68Xy9h7TnT/8i/GI6JjsDDTz7311qfYQtz0crdnyWp5kBKs4sa9oYiWXYDaQlajx9uTEIN2thtdJ8g7b2zxhiDY3cwW/qviOh00DRw5GY2fjtCW384IcIZjvhctGfBxyLHBv7IFn3o5KmdR9+yqCqVof0+3Hxfna6u+szPP+cCpGNbK7yOgAIOk11sRK1HmGEssURY2Jg1TvM5yqBDczF040J3S3yUtwcQFN99tTgRmcTjFYzh04sHwOawECn6xn5uiTDSR3qlIK/tNV/Ad+nwb2dm5S3z/0pcc2A+krDZWjts4n+4MZPbYR9a/K0JuQjQTsGslAozdhXzcVfHfuAfJCl6xFLEAgvbn2sytjB3YF5ChjRFWjZkWInBmoYY=

before_install:
- gem install bundler
- bundle install

deploy:
<<<<<<< HEAD
  provider: releases
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  on:
    tags: true
  verbose: true
  password:
    secure: GfgStezNyiQx7syPyXpbW7Jm+EuY2/4wpIdqOAx6LVKLK5mK++zor+CSp9LK1iveK2CAbnPOz3QXWdjckvkE0vU6GxrFzQmum/eYPDcjph82rhEx8m8nDRKGVTrRsNHNMSqjO1+soEujc+2v+l5AMTxzQCRL3gGf/QCmpxZTVhOtbCYzVCLH4kQge3lZkwKxM9QbNSJXC4IeVBTM8qlzlAk+f3TVCJNeBvrpqjxPlfks7XQmsx9Bpd+3rfbVl4grXUtz/yB36AvUS4cOK19FwIuOsscOfh9PdUhSX2FWS2ixvZEF/XnFELZd5ez6tfaTeCqIdagj4GQ233SHR7eR6Q1ERFYz/U9N90G5q0EuyBM1bSuXx4NczbIRJKfJa3pi1uuyc1baXYlKvsPmCjPBeuYad1g3eGtP3pWKyqG9B+9kAQFXVCoG4GZjH5mX5/Cg6SnmZqegOiXv8doCHg/HlXzchsbegGo3R97chLFN4BHc9+FFMW3xuJRe2ZcpLHfdvzcNTqnwijpQC/kTMzPjD2JIBi7wMnJaPb8nDBnmviF/Ga53u8/xr0jea0pqTDb2q0yXhazkg6fgd6zjF2vqT9knldTqfxsSw+m0oQT1uDxHR5cyPSaJG/uNbePcw5nHEY40WJJhCHbnx7fYs63x4T6uaFRuf5SaWtayLjWiDuY=
env:
  global:
    secure: sZotmEnmoSCTHv8lRyxMuoGVq/FADJ/KnG/qNtY8FGO2rBCA/LRUjI9Pi9S1ZjvSMjwQQEzvdij88JBnGc3VhDiYa17icjnDrKuW2zDM1PNzI1lhJNTwFS56sfTZZZj1oblVY0UG+BWYQmphjV/vcXaz+ce483ozPpeoMnx+Js/r8tUa4Rce+5Rlg/6uxRloin6x30nKAkhAQLIeEqG4VljI6P9jwiWy65DW6ZdgTyN0CGhdH7tGgVPihAt8TH4O2slFNbsRQvdJ5PUZmKF/CB12tvyEr/PT2XXReD3XKnYcetujh++WftTq42Auunj1sEDpJT4ecN28X7j05IUS/O+k75g5zDxnWF9Qdg6RvXSKa4glA2G+4BXrRy48a5dIMAFqKXzl1LsOKacMKmSyN4FBAmQ+LHyVtVSU/BY2ImTjt5GBIfLjAefrsO4J+3jQJXGIvD+3N1/J7TkmFKSfGjuEoOfeLkRmJm4dHWwEkinlubIbW78gPQHSGc2HXaKSy6me5lx7msFn31rmTk1h/La1dzHuCjikxrhJHX9D1d+0vEEbsllPM4ZMF/miwnkyqBMqd6n1QFdv50m7HPjkw+k60EZ+mD2q3LHg/4J6unfXbKPfm9m/dUazZqlxx/r7GFEL9xI2W6038ifsfs0Emvkp7xKUmn77zrSUi/WPkaM=
=======
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    tags: true

env:
  global:
    secure: sZotmEnmoSCTHv8lRyxMuoGVq/FADJ/KnG/qNtY8FGO2rBCA/LRUjI9Pi9S1ZjvSMjwQQEzvdij88JBnGc3VhDiYa17icjnDrKuW2zDM1PNzI1lhJNTwFS56sfTZZZj1oblVY0UG+BWYQmphjV/vcXaz+ce483ozPpeoMnx+Js/r8tUa4Rce+5Rlg/6uxRloin6x30nKAkhAQLIeEqG4VljI6P9jwiWy65DW6ZdgTyN0CGhdH7tGgVPihAt8TH4O2slFNbsRQvdJ5PUZmKF/CB12tvyEr/PT2XXReD3XKnYcetujh++WftTq42Auunj1sEDpJT4ecN28X7j05IUS/O+k75g5zDxnWF9Qdg6RvXSKa4glA2G+4BXrRy48a5dIMAFqKXzl1LsOKacMKmSyN4FBAmQ+LHyVtVSU/BY2ImTjt5GBIfLjAefrsO4J+3jQJXGIvD+3N1/J7TkmFKSfGjuEoOfeLkRmJm4dHWwEkinlubIbW78gPQHSGc2HXaKSy6me5lx7msFn31rmTk1h/La1dzHuCjikxrhJHX9D1d+0vEEbsllPM4ZMF/miwnkyqBMqd6n1QFdv50m7HPjkw+k60EZ+mD2q3LHg/4J6unfXbKPfm9m/dUazZqlxx/r7GFEL9xI2W6038ifsfs0Emvkp7xKUmn77zrSUi/WPkaM=

>>>>>>> 636b280... set travis to push to git hub pages
script: bundle exec fastlane beta
