osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods
branches:
  only:
  - master
  - /.*/
notifications:
  email:
    recipients: "-fodeguipro@gmail.com -henri.m.gil@gmail.com -ismadia09@gmail.com"
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: GurpyBJVZzXNqYX6lhz383uYgZ2HR2PaTjql6GPvtv54behf4mpffhQs3NHF5f8hpqmL+lYCQ6YddixCXN/nr9ZxuA1XA69SyaycUcU93qxP9MEF50BNzqxzNpBgJYcppJlM2eU1S2aeTtGYn+9sK0xPFN9pDtKyhMF1q77d8glkhlf63WJK1fq9RRc5VkrG4Urui89Yst+GB3Q2rXNvVtieZupeulgTfQeTygyVrPQyAEbDg/+Hx1rFavN0jCZ0vpkYARRDJ+jWqrSXaZ6v8ZSeKSUO9l5/ruTOKxtjCOxtS68Xy9h7TnT/8i/GI6JjsDDTz7311qfYQtz0crdnyWp5kBKs4sa9oYiWXYDaQlajx9uTEIN2thtdJ8g7b2zxhiDY3cwW/qviOh00DRw5GY2fjtCW384IcIZjvhctGfBxyLHBv7IFn3o5KmdR9+yqCqVof0+3Hxfna6u+szPP+cCpGNbK7yOgAIOk11sRK1HmGEssURY2Jg1TvM5yqBDczF040J3S3yUtwcQFN99tTgRmcTjFYzh04sHwOawECn6xn5uiTDSR3qlIK/tNV/Ad+nwb2dm5S3z/0pcc2A+krDZWjts4n+4MZPbYR9a/K0JuQjQTsGslAozdhXzcVfHfuAfJCl6xFLEAgvbn2sytjB3YF5ChjRFWjZkWInBmoYY=
before_install:
- openssl aes-256-cbc -K $encrypted_c0bdca35e213_key -iv $encrypted_c0bdca35e213_iv
  -in settings.sh.enc -out settings.sh -d
- gem install bundler
- bundle install
deploy:
  provider: releases
  skip_cleanup: true
  github-token: "$GITHUB_API_TOKEN"
  on:
    tags: true
  verbose: true

#script: bundle exec fastlane to_ci
script: bundle exec fastlane to_ci release:true bump_type:patch

env:
  global:
    secure: JLb5XFS3NJ5GVory1D32wyCTchgW7q0B/nTphVQQriCQZeoamVYfh+g0YVOneOa+vqmITLW/UC0yU0tNNZa9uxWA/zA5jaNNW/GmIaseCjYUYMmGdv5gHSBLrnlKFZja9kseCVKuVmsTnwTE9+s0wRJEhFppMpj+HDgvBxLD4Oi9Hnyiyu3oJzm+1sEVsM0vbd5z4xYFmKqjNiatLHd9Up/KDNUrtUhENf9pEEhsuU6AziDiUM2GE1Vj2L/cukEP6PCuq65HWbQfB76d8wgBss/CGNScxys3nNBMF36MfIiQMeKdOWLtBDUAuVa+onoLe7gI27AYIgxcDyh1GFezhfFsWdTTkXHLhFHwmz7F+ktiGqRyzTRDuqix8cgjvY4wIDyUkNeS6S6fjBWS2zx0COCqV5yHbrRMhrkDf9tJfKobdhTIBgof6JrPGbtDgjhGPbPR1G5B91q8benmN52Tugjc+9VdIjr8AaHd4PWOFrhJQPT9WYkZOPRTKgDFbm8hqtY7gu0Ty6JWaCGPwWdWFOcb1sHN6NxKTDKh6uyebsJD32HSSF5I8zzzYGQxHGihQ7V2WKKPP6jUnUjtAG5vzt98OvxHgII/OZzINIA/59Pgy5UbYqZO/b6laMfKC3xwrO5ZQ910WYlytYcxb7DHLrdLth5kl9iOcX1k4FkBFpo=
