osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients: "-fodeguipro@gmail.com -henri.m.gil@gmail.com -ismadia09@gmail.com"
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: GurpyBJVZzXNqYX6lhz383uYgZ2HR2PaTjql6GPvtv54behf4mpffhQs3NHF5f8hpqmL+lYCQ6YddixCXN/nr9ZxuA1XA69SyaycUcU93qxP9MEF50BNzqxzNpBgJYcppJlM2eU1S2aeTtGYn+9sK0xPFN9pDtKyhMF1q77d8glkhlf63WJK1fq9RRc5VkrG4Urui89Yst+GB3Q2rXNvVtieZupeulgTfQeTygyVrPQyAEbDg/+Hx1rFavN0jCZ0vpkYARRDJ+jWqrSXaZ6v8ZSeKSUO9l5/ruTOKxtjCOxtS68Xy9h7TnT/8i/GI6JjsDDTz7311qfYQtz0crdnyWp5kBKs4sa9oYiWXYDaQlajx9uTEIN2thtdJ8g7b2zxhiDY3cwW/qviOh00DRw5GY2fjtCW384IcIZjvhctGfBxyLHBv7IFn3o5KmdR9+yqCqVof0+3Hxfna6u+szPP+cCpGNbK7yOgAIOk11sRK1HmGEssURY2Jg1TvM5yqBDczF040J3S3yUtwcQFN99tTgRmcTjFYzh04sHwOawECn6xn5uiTDSR3qlIK/tNV/Ad+nwb2dm5S3z/0pcc2A+krDZWjts4n+4MZPbYR9a/K0JuQjQTsGslAozdhXzcVfHfuAfJCl6xFLEAgvbn2sytjB3YF5ChjRFWjZkWInBmoYY=
before_install:
- gem install bundler
- bundle install
deploy:
  provider: releases
  skip_cleanup: true
  github-token: "$GITHUB_TOKEN"
  on:
    tags: true
  verbose: true
  password:
    secure: NLqo2Abm+pj4WRoiCY3UWOzPZ4hfzFwN+vy9X0KlHeczfKUnRyDm+UIiZQuSLvmP32DngYQRUk/jZbx9/coKnANCRemoTZm0rkN7uqsYB1VwP2gKUt/LK2iv55hU0EDAxUq13JRVXfpcVSYhRHbuB+WlP2DLklv/S8lQUYNd8XlNqehSJtabddH6ODsf55FR8Rgmkz3WOmWAWrCOumQpGCGt2tEptu5eRabUMWBd1htkgBMijmpYBzD+VoRrb+uvz0Zo3d9RUgjkIjADMD2E4rMqN+iArsykE7LOeOJsm0JtkFhpQkylOPuv+yDqiGeKPlvto+wUydNiU1OY91hCb7WgvR5NPwsP9R2N4640rHoZUe1jS3KWyyIWNGEXWRXwasS0/37W83WooqfW7/Summ4ovQwEUoDRxxmG+MWU6LJJFVXrBbHTHhhViBm+I3jR0OKavOgP7HxACWQzVAPj9mhtZgCmsnEago5DlDp8R55So4tO3uLU0HA5kTCh8eIf51RsiU9bzmtIGJbK7gAG3sQRvyMj4s+j76XouyYhf5DRQbldRTuHa33wwgh5dE+2NH0M+p2iOE7Oqyr8qFRa41259i0bmeEc2sUL+CVmXWRio5sIwX9adfhJXxxRx8fOuo6R4U9DjRBQCU8xpnQV9kahollg6efYd6+Mfe8K1NI=
  username:
    secure: oeshSdKbBVX2Wx6Dp/l5DG+yKjrcmoZirqgkVXmK5BObdXhvvbLe/0qYLJYNP3FgDYGwYxV/cNOcnBkoR6yhC6Mv4M8q6lRDBSCI5LUyQeqtH0ENQAPHfXii0sDE53LaOPjGja0m1goBlDLqat7Jq59KIvKNozIyPhgK3IdJE+MuKY7NtxReg1jvQGN8LryDEhYwTZBbTOH03htZHXrReJ4oW/9WRludfJZtN1JYpX7gOECl5r0+ANzE7z5MYWsQlcFD5qV03MKJRZShK8Jd63P0IWCRq5VPqAuK91lmIC+LpQBu8TBmCWsTSKdE8D+WCnUnKEqO4x/EOg3BhRWZsQkWAWipvKfGp/RQnnI6L9aX3D8PpgyIFs6S7UGs85etWy1kqP+OUf9EuahJxoVNBfn2oeq5LM+Kb9ZSzfZMkXod+0YKavOcJc/wi1mVi5T5FIlcKdZt4AJCD1xcebqWJBhTlSTk66MhmYXXZ8vE/BkVj52bA3vr5C6QFbzUxY/9/AmZWrtvC55rOVDJctkJ+UgF3X6TUgw8evI8/Geqn9fdPM5OUFe2RxxTOJ5aqCpSLhnXA9FbDoEKNXYhJS1u8Rrh7Ix8C5QNZNOFtPRPejAiW6//1YqA+KuHXepK6YmCv9fV36fPpX1RJ7LQEr0ZR8mQCAFh4Mv/bi5IU20nfmk=
  e-mail:
    secure: c5X4P+afm1k6G+HcNbx49XErZLyLgb9lnR/QUlvuTswvzCyxN4LjKCxNMfDghtCfFCP+rrGaJq94vDhGn+vPeLD2fYll3vnIZ9U6f789ClQv4wnba4eqKVDJh7gQxXmDfijZfpAG7+HYwNJTLfRz5H178VU6V9vg5dH27QL0CE1tUCZQQqFvRWWj/IaNK0bJbXAkFrCGChHY3HlAJwXYocWSQOdMp6aZn8NWyOosUPgC75f+T+k0EU85o4W+YySP9tco9xPHaKxOU19Kvw0av7GpAQCcHnrGvugCRIK0+9YNkPFJbFvo6VERNC5dQD8kpGwsz2iuGI56XSkPyLsA88GGgKHSVwYpxr7oJ9b8q1N69VkbhQ0FB1yBPF7jUvbpHjlsJUu3wTW2tQHksFoqGvbwSHHvONa9KSmjmLcFlrZjxfXTa5neOKVVJutzSqhdjffP//E6f+pSSFCJbOWbuPiTg9fTkcKO3wTtWLuufk3Gbfo8B7sEKKfDJeESu393XrvWza+czakKRl/qkmvM96dG2dSCHFrPKYq++SlqzcgW0aAv9aClXeUWRsuYX2eppENJiJZYrCLpL1QleLHyXvvTSkgwnMwX11Wm6GjQJac0YMjHX6UIyrTXam4iFbBj7HQ7otJpFvUbmu0PPlUkdbHgf3OLmdUt9Y7S6cz44Wc=
env:
  global:
    secure: sZotmEnmoSCTHv8lRyxMuoGVq/FADJ/KnG/qNtY8FGO2rBCA/LRUjI9Pi9S1ZjvSMjwQQEzvdij88JBnGc3VhDiYa17icjnDrKuW2zDM1PNzI1lhJNTwFS56sfTZZZj1oblVY0UG+BWYQmphjV/vcXaz+ce483ozPpeoMnx+Js/r8tUa4Rce+5Rlg/6uxRloin6x30nKAkhAQLIeEqG4VljI6P9jwiWy65DW6ZdgTyN0CGhdH7tGgVPihAt8TH4O2slFNbsRQvdJ5PUZmKF/CB12tvyEr/PT2XXReD3XKnYcetujh++WftTq42Auunj1sEDpJT4ecN28X7j05IUS/O+k75g5zDxnWF9Qdg6RvXSKa4glA2G+4BXrRy48a5dIMAFqKXzl1LsOKacMKmSyN4FBAmQ+LHyVtVSU/BY2ImTjt5GBIfLjAefrsO4J+3jQJXGIvD+3N1/J7TkmFKSfGjuEoOfeLkRmJm4dHWwEkinlubIbW78gPQHSGc2HXaKSy6me5lx7msFn31rmTk1h/La1dzHuCjikxrhJHX9D1d+0vEEbsllPM4ZMF/miwnkyqBMqd6n1QFdv50m7HPjkw+k60EZ+mD2q3LHg/4J6unfXbKPfm9m/dUazZqlxx/r7GFEL9xI2W6038ifsfs0Emvkp7xKUmn77zrSUi/WPkaM=
script: bundle exec fastlane beta
