osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients: "-fodeguipro@gmail.com -henri.m.gil@gmail.com -ismadia09@gmail.com"
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: GurpyBJVZzXNqYX6lhz383uYgZ2HR2PaTjql6GPvtv54behf4mpffhQs3NHF5f8hpqmL+lYCQ6YddixCXN/nr9ZxuA1XA69SyaycUcU93qxP9MEF50BNzqxzNpBgJYcppJlM2eU1S2aeTtGYn+9sK0xPFN9pDtKyhMF1q77d8glkhlf63WJK1fq9RRc5VkrG4Urui89Yst+GB3Q2rXNvVtieZupeulgTfQeTygyVrPQyAEbDg/+Hx1rFavN0jCZ0vpkYARRDJ+jWqrSXaZ6v8ZSeKSUO9l5/ruTOKxtjCOxtS68Xy9h7TnT/8i/GI6JjsDDTz7311qfYQtz0crdnyWp5kBKs4sa9oYiWXYDaQlajx9uTEIN2thtdJ8g7b2zxhiDY3cwW/qviOh00DRw5GY2fjtCW384IcIZjvhctGfBxyLHBv7IFn3o5KmdR9+yqCqVof0+3Hxfna6u+szPP+cCpGNbK7yOgAIOk11sRK1HmGEssURY2Jg1TvM5yqBDczF040J3S3yUtwcQFN99tTgRmcTjFYzh04sHwOawECn6xn5uiTDSR3qlIK/tNV/Ad+nwb2dm5S3z/0pcc2A+krDZWjts4n+4MZPbYR9a/K0JuQjQTsGslAozdhXzcVfHfuAfJCl6xFLEAgvbn2sytjB3YF5ChjRFWjZkWInBmoYY=
before_install:
- openssl aes-256-cbc -K $encrypted_b4338aa57ceb_key -iv $encrypted_b4338aa57ceb_iv
  -in .netrc.enc -out .netrc -d
- gem install bundler
- bundle install
before_deploy:
- git remote set-url origin https://$GH_TOKEN:x-oauth-basic@github.com/4AMOC-iOSFramework/InAppNotificationFramework.git
deploy:
  provider: releases
  skip_cleanup: true
  github-token: "$GH_TOKEN"
  on:
    tags: true
  verbose: true
  username:
    secure: L/c6hQB27Glt90fTOMkUuioGi+9s7q2x2I/hQh3hF9cso8pmDz+AjDV8Xv2MGa0HVUQ+1KPgBNK7HSNefIctYUW57ZjmWb9j0QaDMDxMCBIJ4AH86sr6gxQUrNnRQTU/ZANwT91URf9oNqd5KaCtmXjRLdNpa87GIddBGVxg7fOB4744tn7U2XjD2HqR1WX68SoomTaSElwGAHHgSU9WFAzx9RRzTB9d5KcfmbKT/Eqf9IUmlHyC+3GARs7jUbOY+65PyUYAzuSAoFS6sh68nMvXoIoN24GPLl6uoBsiQb+2/GRgNcvKigL2X/Coxegi687nLd+99YJhRxBzMGxSW9qp1iLAnHfB8jqaX6ihOqFfMtmuewDOp9212TNA7En1crJg6kTYY959EovndSbueax3pGu7b+EvXFy0aqKslEthx0tH26iuhmH3sche9Ot168l0FZZOKDqtWIll6DXqxmhfQ6elPwbWqYF4RiexC9IQD+D0qr1CrISQj6HLzDFU5ufi/ueljFIs80ohopaeW4zOM5E8rgi5gRfAR/M5EEAPDvvxOOpf5JsOBYO28WmiWNLrnUtSsKwGapJVR7IINlZAKK93eOwlU1kGiPFcf01PNe0eIOodlF2FTGJ3OZqj/2Dw+zrCUtdyjUv4ADTPrAxdV3zKjCIGea0tOj3dCKk=
  password:
    secure: eC5yActjDbourZ0tbfSHphEVjr5JTs7um+9uZ1iwnitBojGZIp5ahRj2hGgEY8WSpiJcgkRDkwKf1dKg4lz1MjP1+4BlAphsL6sldxbqr6NIjdLkJSNVUceWAmoQZz0uVsP1dZAgTqhaLJrVDwf0aVyhh638Oz0BWd+P1MK4SC4KTJmsGibw83wnB8hxA5EhfXAnZHe7SL049vkfQ4LEG6xN2JZ1dzqgbKGAEiG0hfbGXMfX7zTLXz+G1JLN1K381gpvgl1szvbryshl7qQBXLjLSWJzP214cvXQQocEExKESQ5uLnYAXmnKWQPZ51xEj9GyKSUUtFKSA6rwnLv39/9nQat5BTink4YOFBo45w2+rb1IF2ACmwtPohMp/fzMq68dJnP0zvzIql0UosunQcKIHZFvNkVxgaZGfml98VKwVMNy9pQ3AjI9g9Az+oxjt/LQSCujqAjJ+c8zmabHubjcL3BOtvmkyj/zyVwFH7KFdKAXhKzwVL9Dkl1tT4n5Fz3/CuO/3Wlry4HgGUqVW1jaACvz9GURrMOBZdwk1M/1sOIx7pOGIvCi/L1kOq3PrSnhAAWcOErXiA97AKTgtuaNjFujITtwUjc7WsHGN1YKtY/UrKTghVaVBrMJdJm1jFTUks/5PTlvLbkjB9fdZMG9jrRULsc4WtFLGZwKyfg=
script: bundle exec fastlane beta
env:
  global:
    secure: e3LERHxeiMa8alskVE0difRLjk0QZhyMnZipXxGwf5XBOuaMTUESlyuq+101KCwFavXBofkFx7VPrx+EJxIqUrqAQvp1jEFbXwjnTWbY03ZcW7TectRjtMbJakcsePGGQwEaeaYBwAjBPz2u8Ll145cB+ytLBVj83G1xuu1a/Hn6i68ixOg99UVTOZowyNrpE5OGMMPanmlRpKHpwiNGiXDv2V6XSZXnsEX3KTSf0hAUDTCtOz+l9gIZx6XPwYPRwGXvJQrYNZfcOI71PuuAvb7AwaPvMXb9yLLSUKK7j0Hu6kKF8pNb5pijYqS0zWLhjczFvhzCM5gTb6nnF1+LbEEJ/5y45V2oOxn1OZGWENg5/TIiLPrWhGmBiEXrLtTPV2BwMeQBEI/C6Q1eq5zrlbgbMCJJDxQp8EDuEeS80rqh6qP0v/d7sinpsRirL5jPdmnqoDVK7xDu0vwrCEb6tomYLgiOcuuHxyQw2Pz0ekXDFXokYFVf92R7U7XvGOtTw12Lj135dBZ8kLTYfSz/DGevGEW0lDQCFKvOJUI4Z3rivhDXf5o4KKweg4pN70fZCaXJOfkILCMuZk/l/BzojvYgzEbiPn4TH+O0Ev+DUDynOA+VUAlCAR/EtdDaT8TzkoQYcszQSqviIlyTv8gRcVaQ6GxVdFZKp5fCLbcM0IU=
