lane :beta do |options|
  #print('\nCurrent version number is\n')
  #increment_version_number(version_number: "1.0.0")
  #print('\n',get_version_number,'\n')


  #)
  #scan()
  if git_branch() == "master"
    #setup_travis
    #login_to_git
    #increment_build_number

    print("\n",ENV["SLACK_URL"],"\n")

    #add_git_tag(tag: get_version_number)
    #push_git_tags
    set_github_release(
      repository_name:"4AMOC-iOSFramework/InAppNotificationFramework",
      api_token: ENV["GH_TOKEN"],
      tag_name: increment_version_number(bump_type: 'patch'),
      commitish: 'master')
    #push_to_git_remote
    version_bump_podspec(path: 'InAppNotificationFramework.podspec',
      version_number: get_version_number)
    beta_deploy
  end
end

lane :test do
  print()
end
lane :beta_deploy do
  pod_lib_lint
  #pod_push
end

after_all do|beta, mesg|
  slack(message:"beta lane successfully ran")
end

error do|beta, exception|
  slack(message: exception.message, success: false)
end
