lane :to_ci do |options|
  #scan
  pod_lib_lint
  if git_branch() == "master"
    if options[:release] and options[:bump_type]
        new_github_release(bump_type: options[:bump_type])
        pod_push
    end
  end
end

lane :new_github_release do |options|
  increment_version_number(bump_type: options[:bump_type])
  set_github_release(
    repository_name:"4AMOC-iOSFramework/InAppNotificationFramework",
    api_token: ENV["GITHUB_API_TOKEN"],
    tag_name: get_version_number,
    commitish: 'master',
    name:get_version_number
  )
  version_bump_podspec(path: 'InAppNotificationFramework.podspec',
    version_number: get_version_number)
end

lane :beta_deploy do
  pod_lib_lint
  pod_push
end

after_all do|_, mesg|
  slack
end

error do|beta, exception|
  slack(message: exception.message, success: false)
end
