before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

lane :beta do |options|
  #scan()
  if git_branch() == "master"
    increment_version_number(bump_type: 'patch')
    increment_version_number(bump_type: 'patch')
    increment_version_number(bump_type: 'patch')
    add_git_tag(tag: get_version_number)
    push_git_tags
    version_bump_podspec(path: 'InAppNotificationFramework.podspec',
      version_number: get_version_number)
    beta_deploy
  end

end

lane :beta_deploy do
  pod_lib_lint
  pod_push
end

after_all do|beta, mesg|
  slack(message:"beta lane successfully ran")
end

error do|beta, exception|
  slack(message: exception.message, success: false)
end
